### PR TITLE
Pointer set fixes

### PR DESCRIPTION
**Pull request by dalle**
Prevent Prototype Pollution #76 for Pointer#set and fix bug with Pointer#set not working with deep paths.

### CODE REVIEW

**Comment by dalle** [comment]
Fixes #95

**Comment by dalle** [comment]
Fixes #96

**Comment by chbrown** [comment]
Cool, thanks. Made some liberal changes but left your authorship in the pertinent commits.

**Comment by chbrown** [comment]
Published as v5.1.0: https://www.npmjs.com/package/rfc6902/v/5.1.0

**Pull request merged**
